name: testeartkeep
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - lib/images/principal-image.png
    - lib/images/the-met.png
    - lib/images/foryou.png
