name: testeartkeep
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  country_list_pick: ^1.0.1+6

  cupertino_icons: ^1.0.2
  firebase_core: ^2.21.0
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - lib/images/principal-image.png
    - lib/images/the-met.png
    - lib/images/foryou.png
    - lib/images/foryou-1.png
    - lib/images/foryou-2.png
    - lib/images/foryou-3.png
    - lib/images/art1.png
    - lib/images/art2.png
    - lib/images/art3.png
    - lib/images/art4.png
    - lib/images/avatar.png
    - lib/images/avatar.svg
    - lib/images/image-8.png
    - lib/images/login-image.png
    - lib/images/rectangle-black.png
    - lib/images/met.png
#
#  fonts:
#    - family: Alfa Slab One
#      fonts:
#        - asset: lib/fonts/AlfaSlabOne-Regular.ttf

